DATASET:
  root_dataset: "/data0/qilei_chen/old_alien/AI_EYE_IMGS/ROP_DATASET_with_label/9LESIONS/"
  list_train: "ridge_in_one_instances_train2014.json"
  list_val: "ridge_in_one_instances_train2014.json"
  img_folder_train: "train2014"
  img_folder_val: "train2014"
  num_class: 2
  imgSizes: (1200)
  imgMaxSize: 1600
  padding_constant: 4
  segm_downsampling_rate: 4
  random_flip: True

MODEL:
  arch_encoder: "resnet50"
  arch_decoder: "upernet"
  fc_dim: 2048

TRAIN:
  batch_size_per_gpu: 1
  num_epoch: 25
  start_epoch: 15
  epoch_iters: 3000
  optim: "SGD"
  lr_encoder: 0.02
  lr_decoder: 0.02
  lr_pow: 0.9
  beta1: 0.9
  weight_decay: 1e-4
  deep_sup_scale: 0.4
  fix_bn: False
  workers: 16
  disp_iter: 20
  seed: 304

VAL:
  visualize: True
  checkpoint: "epoch_15.pth"

TEST:
  checkpoint: "epoch_15.pth"
  result: "train_result_epoch15/"

DIR: "ropridge/ropridge-resnet50-upernet"
