DATASET:
  root_dataset: "/data0/qilei_chen/old_alien/AI_EYE_IMGS/ROP_DATASET_with_label/9LESIONS/"
  list_train: "ridge_in_three_instances_train2014.json"
  list_val: "ridge_in_three_instances_val2014.json"
  img_folder_train: "train2014"
  img_folder_val: "val2014"
  num_class: 4
  imgSizes: (1200)
  imgMaxSize: 1600
  padding_constant: 4
  segm_downsampling_rate: 4
  random_flip: True

MODEL:
  arch_encoder: "resnet50"
  arch_decoder: "upernet"
  fc_dim: 2048

TRAIN:
  batch_size_per_gpu: 1
  num_epoch: 30
  start_epoch: 0
  epoch_iters: 3000
  optim: "SGD"
  lr_encoder: 0.02
  lr_decoder: 0.02
  lr_pow: 0.9
  beta1: 0.9
  weight_decay: 1e-4
  deep_sup_scale: 0.4
  fix_bn: False
  workers: 20
  disp_iter: 20
  seed: 304
  class_weight: [1.0,9.0]
VAL:
  visualize: True
  checkpoint: "epoch_26.pth"

TEST:
  checkpoint: "epoch_2.pth"
  result: "test"

DIR: "ropridge/ropridge3-resnet50-upernet"
